// vue/src/components/tools/BpmnForm.vue
<template>
    <div ref="formContainer"></div>
  </template>
  
  <script>
  import { ref, onMounted, defineComponent, toRefs, watch } from 'vue';
  import { Form } from '@bpmn-io/form-js';
  import "@bpmn-io/form-js-viewer/dist/assets/form-js.css";
  
  export default defineComponent({
    name: 'BpmnForm',
    props: {
      schema: Object,
      data: Object,
    },
    emits: ['form-submit'],
    setup(props, { emit }) {
      const formContainer = ref(null);
      const formInstance = ref(null); // Use ref to track the form instance
  
      onMounted(() => {
        if (formContainer.value) {
          formInstance.value = new Form({
            container: formContainer.value,
          });
  
          formInstance.value.on('submit', (event) => {
            emit('form-submit', event.data);
          });
  
          formInstance.value.importSchema(props.schema, props.data).catch(err => {
            console.error('Failed to import schema:', err);
          });
        }
      });
  
      const submitForm = () => {
        if (formInstance.value) {
          formInstance.value.submit();
        } else {
          console.error('Form instance is not initialized');
        }
      };
  
      return {
        formContainer,
        submitForm,
      };
    },
  });
  </script>
  
  <style scoped>
  /* Add your styles here */
  </style>

// react_bootstrap/src/components/BpmnForm.tsx
import React, {
  useEffect,
  useRef,
  useImperativeHandle,
  forwardRef,
} from "react";
import { Form } from "@bpmn-io/form-js";
import "@bpmn-io/form-js-viewer/dist/assets/form-js.css";

interface BpmnFormProps {
  schema: object;
  onFormSubmit?: (data: any) => void;
  onFormCreated?: (form: any) => void;
}

const BpmnForm = forwardRef<{ submitForm: () => void }, BpmnFormProps>(
  ({ schema, onFormSubmit, onFormCreated }, ref) => {
    const formRef = useRef<HTMLDivElement | null>(null);
    const formInstanceRef = useRef<any>(null);

    useEffect(() => {
      if (formRef.current) {
        const form = new Form({
          container: formRef.current,
        });

        form.on("submit", (event: any) => {
          if (onFormSubmit) {
            onFormSubmit(event.data); // Pass the form data to the parent component
          }
        });

        form
          .importSchema(schema)
          .then(() => {
            formInstanceRef.current = form;
            if (onFormCreated) {
              onFormCreated(form);
            }
          })
          .catch((err: Error) => {
            console.error("Failed to import form", err);
          });

        return () => {
          form.destroy();
        };
      }
    }, [schema, onFormSubmit, onFormCreated]);

    // Expose the submitForm method to the parent component
    useImperativeHandle(ref, () => ({
      submitForm: () => {
        if (formInstanceRef.current) {
          formInstanceRef.current.submit();
        }
      },
    }));

    return <div ref={formRef} />;
  }
);

export default BpmnForm;
